<?php
/**
 * Created by PhpStorm.
 * User: aa
 * Date: 2019/1/17
 * Time: 20:46
 */

namespace app\wycadmin\controller;


use app\common\controller\admin\AdminBase;
use app\common\lib\IAuth;
use think\Controller;

class Login extends AdminBase
{
    protected function _initialize()
    {
     //   parent::_initialize (); // TODO: Change the autogenerated stub
    }

    /**
     * get = 登录页面跳转  post = 验证账号密码
     * @return mixed|void
     * @throws \think\exception\DbException
     */
    public function index(){
        if(request ()->isGet ()){
            $isLogin = $this->isLogin ();
            if($isLogin){
                return $this->redirect ('index/index');
            }else{
                return $this->fetch ();
            }
        }elseif (request ()->isPost ()){
            $data = input ('post.');
            if(!captcha_check ($data['captcha'])){
             //   $this->error('验证码错误');
            }
            //判断usernamne password
            //validate机制
                    $user = model ('AdminUser')
                        ->get (['username' => $data['username'],'status'=>1]);
                if(!$user){
                    $this->error ('该用户不存在');
                }
                //在对密码进行校验
                if(IAuth::setPassword ($data['password']) != $user->password){
                    $this->error ('密码不正确');
                }
                // 1 更新数据库 登录时间 ip
                $udata = [
                    'logins' => $user->logins +1,
                    'last_login_time' => time (),
                    'last_login_ip' => request ()->ip (),
                ];
                try{
                    model ('AdminUser')->save ($udata,['id'=>$user->id]);
                }catch (Exception $e){
                    $this->error ($e->getMessage ());
                    //$this->error ($e->getMessage ());
                }
                session (config ('admin.session_user'),$user,config ('admin.session_user_scope'));
                $this->success('登录成功','index/index');
            }
        }


    /**
     * 退出登录
     */
    public function logout(){
        session (null,config ('admin.session_user_scope'));
        $this->redirect ('login/index');
    }
}