<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/19
 * Time: 15:08
 */

namespace app\common\controller\index;


use app\common\controller\Base;
use think\Cookie;

class IndexBase extends Base
{
    protected $success = 1;
    protected $error = 0;
    protected $userId = 0;
    protected $listRows = 8;
    protected $userInfo = null;
    protected $fanmang = '系统繁忙,请稍后再试';
    //protected $page = [];

    protected function _initialize()
    {
        parent::_initialize (); // TODO: Change the autogenerated stub
        $this->userId = Cookie::get ('user_id');
       // $this->userInfo = $this->getUserInfo ();

    }





    protected function getUserInfo(){
        $memberInfo = model ('Member')
            ->where('id',$this->userId)
            ->find();
        if ($memberInfo && $memberInfo->status == $this->normal){
            return $memberInfo;
        }elseif ($memberInfo){
            return $this->error ('该账号已被封禁','login/login');
        }
        return  $this->redirect ('login/login');
    }


}